// Cross-zone spine chaining for the Europe march. QuestFactory uses this as each
// zone's entryPrerequisite. Home cities have none (their chains are class-gated
// via classRequirement = the zone's homeClass). Groups mean "any one satisfies."
export type EntryPrereq = (string | { anyOf: string[] })[];

export const ENTRY_PREREQUISITES: Record<string, EntryPrereq> = {
  'campania-shadow': ['rom-04-appian-gate'],
  'apulia-eastern-dock': ['cam-03-buried-relics'],
  'epirus-landing': ['apu-02-harbor-corsairs'],
  'thessaloniki-outpost': [{ anyOf: ['var-02-march-provisions', 'epi-02-march-inland'] }],
  'thermopylae-pass': ['eu-02-first-harvest'],
  'delphi-sanctuary': ['eu-10-final-harvest'],
  'karelia-lakes': ['mur-04-harbor-evil'],
  'smolensk-gate': ['kar-02-dead-wagons'],
  'bryansk-woodland': ['mos-04-beneath-walls'],
  'kyiv-river-gate': [{ anyOf: ['bry-02-familiar-colors', 'smo-02-river-ford'] }],
  'carpathian-crossing': ['kyi-02-combined-caravan'],
  'tyrol-forge-road': ['mun-04-forge-raid'],
  'alps-high-pass': [{ anyOf: ['bur-02-road-ambushers', 'tyr-03-pass-supplies'] }],
  'vienna-river-muster': ['alp-02-ambush-ring'],
  'belgrade-iron-river': [{ anyOf: ['vie-02-dock-saboteurs', 'car-02-defile-convoy'] }],
  'vardar-corridor': ['bel-02-confluence-warlord'],
  'kent-passage': ['lon-04-first-evil'],
  'calais-landing': ['ken-02-passage-papers'],
  'paris-veiled-lights': ['cal-02-beach-raiders'],
  'burgundy-vintners-road': ['par-02-catacomb-casters'],
  // ── AFRICA — the Rift march (append-only) ──
  'luxor-valley-of-kings': ['cai-04-first-evil'],
  'aswan-first-cataract': ['lux-02-relic-south'],
  'nubia-black-pyramids': ['asw-02-gate-of-nubia'],
  'sudd-drowned-road': ['nub-02-pyramid-fields'],
  'ituri-green-cathedral': ['kin-04-first-evil'],
  'virunga-smoke-mountains': ['itu-03-lakes-medicine'],
  'victoria-source': [{ anyOf: ['sud-02-through-the-reeds', 'vir-02-refugees-to-the-lake'] }],
  'serengeti-long-grass': ['vic-02-caravan-south'],
  'ngorongoro-outpost': ['ser-02-rift-warden'],
  'rift-descent': ['af-02-first-harvest'],
  'olduvai-cradle': ['af-10-final-harvest'],
  // ── ASIA — the Kunlun march (append-only) ──
  'changtang-empty-crossing': ['lha-04-first-evil'],
  'hoh-xil-roof-of-world': ['cht-03-high-road-supplies'],
  'setouchi-inland-sea': ['kyo-04-first-evil'],
  'shanghai-eastern-dock': ['set-02-passage-west'],
  'three-gorges-river-teeth': ['sha-02-river-mouth'],
  'sichuan-red-basin': ['gor-02-river-teeth-convoy'],
  'java-temple-shore': ['bal-04-first-evil'],
  'bangkok-delta-gate': ['jav-02-crossing-offering'],
  'angkor-stone-map': ['ban-02-north-road'],
  'yunnan-cloud-steps': ['ang-02-temple-warden'],
  'kham-eastern-plateau': [{ anyOf: ['sic-02-climb-provisions', 'yun-02-up-to-plateau'] }],
  'kunlun-jade-gate': [{ anyOf: ['hox-02-pilgrims-to-the-gate', 'kha-02-caravan-to-the-gate'] }],
  'kunlun-ascent': ['as-02-first-harvest'],
  'kunlun-jade-court': ['as-10-final-harvest'],
  // ── BABEL — the Assassin's road (append-only) ──
  'pearl-coast': ['dub-04-first-evil'],
  'mesopotamian-marshes': ['prl-03-past-the-coves'],
  'shinar-muster': ['mar-03-through-the-channels'],
  'processional-way': ['bb-02-first-harvest'],
  'etemenanki-stair': ['bb-10-final-harvest'],
  // ── ULURU — the Hunter's songline (append-only) ──
  'blue-mountains-veil': ['syd-04-first-evil'],
  'red-track': ['blu-02-water-for-the-track'],
  'dry-heart': ['red-02-songline-walkers'],
  'desert-muster': ['dry-02-last-water'],
  'songlines-end': ['ul-02-first-harvest'],
  'uluru-heart-stone': ['ul-10-final-harvest'],
  // ── TEOTIHUACAN — the Savage's tour (append-only) ──
  'oaxaca-cloud-valley': ['mex-04-first-evil'],
  'palenque-jungle-court': ['oax-02-zapotec-seal'],
  'yucatan-serpent-steps': ['pal-02-jungle-dark'],
  'veracruz-olmec-shore': ['yuc-02-cenote-offering'],
  'valley-muster': ['ver-02-caravan-home'],
  'avenue-of-the-dead': ['te-02-first-harvest'],
  'teotihuacan-birthplace': ['te-10-final-harvest'],
};
