// GROUND-LAYER RASTER GENERATOR (offline tool — run: node tools/generateEarthRaster.mjs)
//
// Builds the compact Earth land/water + coarse-biome raster the sparse-world
// ground renderer samples (src/world/earth-raster-data.ts).
//
// SOURCE + LICENSE: Natural Earth 110m "land" polygons (naturalearthdata.com),
// fetched from https://raw.githubusercontent.com/nvkelso/natural-earth-vector/
// master/geojson/ne_110m_land.geojson. Natural Earth is PUBLIC DOMAIN: "Free
// for use in any type of project... no permission needed, no attribution
// required." Only the derived raster is committed, not the source polygons.
//
// OUTPUT: a 720x360 grid (0.5 deg per cell, row 0 = 90N, col 0 = 180W), one
// byte per cell: 0 = water, 1..5 = coarse latitude-band biome class (tropical /
// arid / temperate / boreal / polar). Run-length encoded + base64 so the whole
// planet bundles at a few tens of KB.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const SRC_URL = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson';
const LOCAL = process.argv[2]; // optional: path to a local ne_110m_land.geojson
const W = 720;
const H = 360;
const DEG = 0.5;

const geo = LOCAL && existsSync(LOCAL) ? JSON.parse(readFileSync(LOCAL, 'utf8')) : JSON.parse(await (await fetch(SRC_URL)).text());

// Collect every polygon as {bbox, rings} — even-odd raycast across ALL rings
// of a polygon handles holes automatically.
const polys = [];
for (const f of geo.features) {
  const g = f.geometry;
  const multi = g.type === 'MultiPolygon' ? g.coordinates : [g.coordinates];
  for (const rings of multi) {
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    for (const ring of rings) for (const [x, y] of ring) {
      if (x < minX) minX = x; if (x > maxX) maxX = x;
      if (y < minY) minY = y; if (y > maxY) maxY = y;
    }
    polys.push({ bbox: [minX, minY, maxX, maxY], rings });
  }
}

function isLand(lng, lat) {
  for (const p of polys) {
    const [x0, y0, x1, y1] = p.bbox;
    if (lng < x0 || lng > x1 || lat < y0 || lat > y1) continue;
    let inside = false;
    for (const ring of p.rings) {
      for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
        const [xi, yi] = ring[i];
        const [xj, yj] = ring[j];
        if (yi > lat !== yj > lat && lng < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) inside = !inside;
      }
    }
    if (inside) return true;
  }
  return false;
}

/** Coarse biome by latitude band (deliberately crude — gray-box classes). */
function biomeClass(lat) {
  const a = Math.abs(lat);
  if (a >= 60) return 5; // polar / tundra
  if (a >= 48) return 4; // boreal
  if (a >= 32) return 3; // temperate
  if (a >= 16) return 2; // arid belt
  return 1; // tropical
}

const grid = new Uint8Array(W * H);
for (let row = 0; row < H; row++) {
  const lat = 90 - (row + 0.5) * DEG;
  for (let col = 0; col < W; col++) {
    const lng = -180 + (col + 0.5) * DEG;
    grid[row * W + col] = isLand(lng, lat) ? biomeClass(lat) : 0;
  }
}

// RLE: [count-hi, count-lo, value] triplets, then base64.
const runs = [];
let val = grid[0];
let count = 0;
for (const v of grid) {
  if (v === val && count < 65535) count++;
  else {
    runs.push((count >> 8) & 0xff, count & 0xff, val);
    val = v;
    count = 1;
  }
}
runs.push((count >> 8) & 0xff, count & 0xff, val);
const b64 = Buffer.from(Uint8Array.from(runs)).toString('base64');

const land = grid.reduce((n, v) => n + (v > 0 ? 1 : 0), 0);
const out = `// GENERATED by tools/generateEarthRaster.mjs — do not hand-edit.
//
// Earth land/water + coarse-biome raster for the sparse-world GROUND LAYER.
// Grid: ${W}x${H} cells, ${DEG} deg/cell, row 0 = 90N, col 0 = 180W.
// Classes: 0 water, 1 tropical, 2 arid, 3 temperate, 4 boreal, 5 polar.
//
// SOURCE + LICENSE: derived from Natural Earth 110m land polygons
// (naturalearthdata.com) — Natural Earth is PUBLIC DOMAIN (free for any use,
// no permission or attribution required). Biome classes are latitude bands
// added by the generator (not part of the source data).
export const EARTH_RASTER_W = ${W};
export const EARTH_RASTER_H = ${H};
export const EARTH_RASTER_DEG = ${DEG};
/** Run-length encoded grid: base64 of [countHi, countLo, class] triplets. */
export const EARTH_RASTER_RLE_B64 =
  '${b64.replace(/(.{100})/g, "$1' +\n  '")}';
`;
writeFileSync('src/world/earth-raster-data.ts', out);
console.log(`land cells: ${land}/${W * H} (${((100 * land) / (W * H)).toFixed(1)}%)`);
console.log(`rle bytes: ${runs.length}  base64 chars: ${b64.length}  file bytes: ${out.length}`);
